export const menuInfos = [
    {title: '甜品', icon: require('./img/home/menuview/fork.png'), color: '#E51C23'},
    {title: '西餐', icon: require('./img/home/menuview/cutlery.png'), color: '#FFC125'},
    {title: '品牌餐饮', icon: require('./img/home/menuview/maxcdn.png'), color: '#E51C2A'},
    {title: '自助餐', icon: require('./img/home/menuview/beer.png'), color: '#3F51B5'},
    {title: '小吃快餐', icon: require('./img/home/menuview/pizza.png'), color: '#50B53F'},
    {title: '咖啡酒吧', icon: require('./img/home/menuview/coffee.png'), color: '#8B5A2B'},
    {title: '生日聚会', icon: require('./img/home/menuview/cake.png'), color: '#FF4081'},
    {title: '更多', icon: require('./img/home/menuview/angle-right.png'), color: '#2977B2'},
]

export const recommend = 'http://api.meituan.com/group/v1/recommend/homepage/city/1?__skck=40aaaf01c2fc4801b9c059efcd7aa146&__skcy=mrUZYo7999nH8WgTicdfzaGjaSQ=&__skno=51156DC4-B59A-4108-8812-AD05BF227A47&__skts=1434530933.303717&__skua=bd6b6e8eadfad15571a15c3b9ef9199a&__vhost=api.mobile.meituan.com&ci=1&client=iphone&limit=40&movieBundleVersion=100&msid=48E2B810-805D-4821-9CDD-D5C9E01BC98A2015-06-17-14-50363&offset=0&position=39.983497,116.318042&userId=10086&userid=10086&utm_campaign=AgroupBgroupD100Fab_chunceshishuju__a__a___b1junglehomepagecatesort__b__leftflow___ab_gxhceshi__nostrategy__leftflow___ab_gxhceshi0202__b__a___ab_pindaochangsha__a__leftflow___ab_xinkeceshi__b__leftflow___ab_gxtest__gd__leftflow___ab_gxh_82__nostrategy__leftflow___ab_pindaoshenyang__a__leftflow___i_group_5_2_deallist_poitype__d__d___ab_b_food_57_purepoilist_extinfo__a__a___ab_trip_yidizhoubianyou__b__leftflow___ab_i_group_5_3_poidetaildeallist__a__b___ab_waimaizhanshi__b__b1___a20141120nanning__m1__leftflow___ab_pind'

export const haidilaoInfos = [
    {
        title: '锅底',
        id: 1,
        data:[
            {
                name:'鸳鸯锅底',
                monthlySale:1228,
                like:329,
                price:38,
                icon: require('./img/restaurant/yuanyangguodi.jpeg'),
            },
            {
                name:'B锅底',
                monthlySale:128,
                like:38,
                price:38,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'C锅底',
                monthlySale:128,
                like:38,
                price:38,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'D锅底',
                monthlySale:128,
                like:38,
                price:38,
                icon: require('./img/restaurant/blank.png'),
            },
        ],
    },
    {
        title:'招牌菜品',
        id: 2,
        data: [
            {
                name:'招牌虾滑',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/zhaopaixiahua.jpeg'),
            },
            {
                name:'招牌A',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'招牌B',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'招牌C',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'招牌D',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'招牌E',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'招牌F',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
        ],
    },
    {
        title:'荤菜',
        id: 3,
        data: [
            {
                name:'鲜嫩肥牛',
                monthlySale:128,
                like:39,
                price:42.5,
                icon: require('./img/restaurant/feiniu.jpeg'),
            },
            {
                name:'荤菜A',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'荤菜B',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'荤菜C',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
        ],
    },
    {
        title:'素菜',
        id: 4,
        data:[
            {
                name:'鱼豆腐',
                monthlySale:428,
                like:19,
                price:23.5,
                icon: require('./img/restaurant/yudoufu.png'),
            },
            {
                name:'素菜A',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'素菜B',
                monthlySale:428,
                like:129,
                price:56,
                icon: require('./img/restaurant/blank.png'),
            },
        ],
    },
    {
        title:'饮料酒水',
        id: 5,
        data: [
            {
                name:'酒水A',
                monthlySale:428,
                like:129,
                price:18,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'酒水B',
                monthlySale:428,
                like:129,
                price:18,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'酒水C',
                monthlySale:428,
                like:129,
                price:18,
                icon: require('./img/restaurant/blank.png'),
            },
        ],
    },
    {
        title:'小料',
        id: 6,
        data: [
            {
                name:'小料A',
                monthlySale:428,
                like:129,
                price:5,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'小料B',
                monthlySale:428,
                like:129,
                price:5,
                icon: require('./img/restaurant/blank.png'),
            },
        ],
    },
    {
        title:'小吃',
        id: 7,
        data: [
            {
                name:'小吃A',
                monthlySale:428,
                like:129,
                price:15,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'小吃B',
                monthlySale:428,
                like:129,
                price:15,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'小吃C',
                monthlySale:428,
                like:129,
                price:15,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'小吃D',
                monthlySale:428,
                like:129,
                price:15,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'小吃E',
                monthlySale:428,
                like:129,
                price:15,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'小吃F',
                monthlySale:428,
                like:129,
                price:15,
                icon: require('./img/restaurant/blank.png'),
            },
            {
                name:'小吃G',
                monthlySale:428,
                like:129,
                price:15,
                icon: require('./img/restaurant/blank.png'),
            },
        ],
    },
]